User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
> python3.7 ~/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda --version
> pyenv root
> conda info --json
> pyenv root
Python interpreter path: /usr/bin/python3
Starting Pylance language server.
Error 2021-06-26 13:09:54: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/root/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file '/root/.config/Code/User/settings.json')
	at _handleError (/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:156171)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:581560)
	at async /root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580687
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
Error 2021-06-26 13:09:54: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/mxolisi/Documents/Codes/Python/marketplaceio/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/mxolisi/Documents/Codes/Python/marketplaceio/.vscode/settings.json')
	at _handleError (/snap/code/65/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:156171)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:581560)
	at async /root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/root/.vscode/extensions/ms-python.python-2021.5.926500501/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
> conda --version
